# -*- coding: utf-8 -*-
"""evaluate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z53L4jzdBZFgcqSvMKwYOIc07jfblcsy
"""

import pandas as pd
import torch

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix
)

from preprocess import preprocess_dataframe


MODEL_PATH = "./best_model"

TEST_PATH = "../data/test.csv"

USE_CONTEXT = True
REMOVE_EMOJI = False


# -----------------------
# LOAD DATA
# -----------------------

test_df = pd.read_csv(TEST_PATH)

test_df = preprocess_dataframe(
    test_df,
    use_context=USE_CONTEXT,
    remove_emoji=REMOVE_EMOJI
)


# -----------------------
# TOKENIZER
# -----------------------

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)


def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )


test_dataset = Dataset.from_pandas(
    test_df[["text", "label"]]
)

test_dataset = test_dataset.map(
    tokenize,
    batched=True
)

test_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)


# -----------------------
# MODEL
# -----------------------

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_PATH
)


# -----------------------
# PREDICT
# -----------------------

trainer = Trainer(model=model)

predictions = trainer.predict(test_dataset)

preds = torch.argmax(
    torch.tensor(predictions.predictions),
    dim=-1
).numpy()

labels = test_df["label"].values


# -----------------------
# REPORT
# -----------------------

print(classification_report(labels, preds))

print(confusion_matrix(labels, preds))