# -*- coding: utf-8 -*-
"""preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z53L4jzdBZFgcqSvMKwYOIc07jfblcsy
"""

pip install torch transformers datasets scikit-learn pandas emoji tqdm matplotlib seaborn

import pandas as pd
import emoji
import re


def remove_emojis(text):
    return emoji.replace_emoji(text, replace='')


def clean_text(text):
    text = str(text)

    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)

    return text.strip()


def build_input(reply, parent=None, use_context=False):
    if use_context and parent:
        return f"[CTX] {parent} [REPLY] {reply}"

    return reply


def preprocess_dataframe(df, use_context=False, remove_emoji=False):

    processed_texts = []

    for _, row in df.iterrows():

        reply = clean_text(row["reply"])
        parent = clean_text(row["parent"])

        if remove_emoji:
            reply = remove_emojis(reply)
            parent = remove_emojis(parent)

        text = build_input(
            reply,
            parent,
            use_context=use_context
        )

        processed_texts.append(text)

    df["text"] = processed_texts

    return df