# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z53L4jzdBZFgcqSvMKwYOIc07jfblcsy
"""

import pandas as pd
import torch

from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

from sklearn.metrics import accuracy_score, f1_score

from preprocess import preprocess_dataframe


MODEL_NAME = "roberta-base"


# -----------------------
# CONFIG
# -----------------------

USE_CONTEXT = True
REMOVE_EMOJI = False

TRAIN_PATH = "../data/train.csv"
VAL_PATH = "../data/val.csv"

OUTPUT_DIR = "./results"


# -----------------------
# LOAD DATA
# -----------------------

train_df = pd.read_csv(TRAIN_PATH)
val_df = pd.read_csv(VAL_PATH)

train_df = preprocess_dataframe(
    train_df,
    use_context=USE_CONTEXT,
    remove_emoji=REMOVE_EMOJI
)

val_df = preprocess_dataframe(
    val_df,
    use_context=USE_CONTEXT,
    remove_emoji=REMOVE_EMOJI
)


# -----------------------
# TOKENIZER
# -----------------------

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)


def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )


train_dataset = Dataset.from_pandas(
    train_df[["text", "label"]]
)

val_dataset = Dataset.from_pandas(
    val_df[["text", "label"]]
)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)

train_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

val_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)


# -----------------------
# MODEL
# -----------------------

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)


# -----------------------
# METRICS
# -----------------------

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = torch.argmax(
        torch.tensor(logits),
        dim=-1
    )

    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions)

    return {
        "accuracy": acc,
        "f1": f1
    }


# -----------------------
# TRAINING ARGS
# -----------------------

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,

    evaluation_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=3,

    weight_decay=0.01,

    logging_steps=50,

    load_best_model_at_end=True
)


# -----------------------
# TRAINER
# -----------------------

trainer = Trainer(
    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=val_dataset,

    tokenizer=tokenizer,

    compute_metrics=compute_metrics
)


# -----------------------
# TRAIN
# -----------------------

trainer.train()

trainer.save_model("./best_model")